### ISSUE TITLE
make Python 3 compatible

### ISSUE THREAD

**Issue by gfairchild** [s-block/django-nested-inline#22]
I'm running Django 1.7.1 and Python 3.4.x. I pip installed django-nested-inline, so I have 0.3.3. I was hoping to use django-nested-inline on a project I'm working on now, but it doesn't appear to be Python 3 compatible.

    Traceback (most recent call last):
      File "/srv/www/swap/public_html/webapp/wsgi.py", line 39, in <module>
        application = get_wsgi_application()
      File "/srv/www/swap/public_html/env/lib/python3.4/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
        django.setup()
      File "/srv/www/swap/public_html/env/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/srv/www/swap/public_html/env/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
        app_config.ready()
      File "/srv/www/swap/public_html/env/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 22, in ready
        self.module.autodiscover()
      File "/srv/www/swap/public_html/env/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
        autodiscover_modules('admin', register_to=site)
      File "/srv/www/swap/public_html/env/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
        import_module('%s.%s' % (app_config.name, module_to_search))
      File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/srv/www/swap/public_html/env/lib/python3.4/site-packages/nested_inline/admin.py", line 8, in <module>
        from django.utils.encoding import force_unicode
    ImportError: cannot import name 'force_unicode'

Looking at the [force_unicode documentation](https://docs.djangoproject.com/en/1.7/ref/utils/#django.utils.encoding.force_unicode), this is an old function call that only works under Python 2.

**Comment by s-block** [comment]
0.3.4
